### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by giacomov** [conda-forge/wcslib-feedstock#4]
Thank you very much for providing this!

I propose some small changes:

* update to 5.17
* use the official heasarc path for the archive:

```
{% set name = "wcslib" %}
{% set version = "5.17" %}
{% set sha256 = "5c9cb5c86be01703f6488774ef3ea44fd6918a4dcdfddc70855905c05de8436c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{name}}-{{version}}.tar.bz2
  url: ftp://ftp.atnf.csiro.au/pub/software/{{name}}/{{name}}-{{version}}.tar.bz2
  sha256: {{ sha256 }}
```

If you want I can open a pull request for this.

Cheers,
